spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3001/infoclients?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: logranda
    hikari:
      data-source-properties:
        connectionTimeout: 30000
        minimumIdle: 5
        maximumPoolSize: 5
        poolName: RapicreditPool
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        connectionTestQuery: SELECT 1
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        hibernate.cache.hazelcast.instance_name: RapicreditCore
        hibernate.cache.use_minimal_puts: true
        hibernate.cache.hazelcast.use_lite_member: true
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
